config/routes.rb
Rails.application.routes.draw do
  resources :workers do 
    resources :reviews,except: [:show,:index]
  end
  get 'head/index'
  get 'workers/new'
  get 'home/index'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",registrations: "users/registrations"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions",registrations: "admins/registrations"}
  root to: 'home#index'
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :admin
  has_many :reviews
  has_attached_file :image, styles: { small: "200x300#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!,except: [:index,:show]
  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all.includes(:reviews)
    if current_user
      redirect_to worker_path(current_user)
    end
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    @reviews= Review.where(worker_id: @worker.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review=0
    else
      @avg_review=@reviews.average(:rating).round(2)
    end
  end

  # GET /workers/new
  def new
    @worker = current_admin.workers.build
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = current_admin.workers.build(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:title, :mobile_no, :hostel, :rating, :image)
    end
end

app/helpers/worker_helper.rb
module WorkerHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div>
  <div class="field">
    <%= f.label :hostel %><br>
    <%= f.text_field :hostel %>
  </div>
  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<% if (!user_signed_in?&&!admin_signed_in?) %>
  <div class="jumbotron">
    <h2>Your Favorite Worker Reviewed</h2>
    <p>Give a review to the housekeeping service provided</p>
    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-md" %></p>
  </div>
<% end %>

<div class="row">
  <% @workers.each do |worker| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag worker.image.url(:small), class: 'image'), worker %>
        <%= link_to worker.title,worker %>
      </div>
    </div>
  <% end %>
</div>
<% if current_admin %>
<%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
<% elsif current_user %>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<% end %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @worker.image.url(:small) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length}" %> reviews </em>
        <div class="table-responsive">
          <table class="table">
            <p>
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @worker.title %></td>
              </tr>
              <tr>
                <td><strong>Mobile No.:</strong></td>
                <td><%= @worker.mobile_no %></td>
              </tr>
              <tr>
                <td><strong>Hostel:</strong></td>
                <td><%= @worker.hostel %></td>
              </tr>
            </tbody>
          </p>
          </table>
          <% if user_signed_in? %>
          <%= link_to 'Write a Review', new_worker_review_path(@worker) %>
          <% end %>
        </div>
        <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_worker_path(@worker) %>
        <% end %>
</div>
<div class="col-md-6 col-md-offset-1">
        <h1 class="review_title"><%= @worker.title %></h1>
        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_worker_review_path(@worker), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
        <div class="container">
          <div class="row">
            <div class="col-md-8">
              <div class="comments-list">
                    <p class="pull-right">
                    <strong>Title:</strong>
                    <%= review.name %>
                    <strong>Mobile No.:</strong>
                    <%= review.mobile_no %>
                    <strong>Time in:</strong>
                    <%= review.time_in %>
                    <strong>Time out:</strong>
                    <%= review.time_out %>
                    <br>
                    <div class="star-rating" data-score= <%= review.rating %> ></div>
                </p>
              </div>
            </div>
          </div>
        </div>
          <% end %>
        <% end %>
</div>
</div>
</div>
</div>
<% if current_admin %>
<%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
<% elsif current_user %>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<% end %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>