config/routes.rb
Rails.application.routes.draw do
  resources :workers do 
    resources :reviews,except: [:show,:index]
  end
  get 'head/index'
  get 'workers/new'
  get 'home/index'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",registrations: "users/registrations"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions",registrations: "admins/registrations"}
  root to: 'home#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_worker
  # GET /reviews
  # GET /reviews.json
  # GET /reviews/newe
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.worker_id=@worker.id
    if @review.save
      redirect_to @worker
    else
      render 'new'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    @review.update(review_params)
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    def set_worker
      @worker = Worker.find(params[:worker_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :name, :mobile_no, :time_in, :time_out)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@worker,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div>
  <div class="field">
    <%= f.label :time_in %><br>
    <%= f.datetime_select :time_in %>
  </div>
  <div class="field">
    <%= f.label :time_out %><br>
    <%= f.datetime_select :time_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>
|
<%= link_to 'Back', worker_path(@worker) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', worker_path(@worker) %>