config/routes.rb
Rails.application.routes.draw do
  resources :workers do 
    resources :reviews,except: [:show,:index]
  end
  get 'head/index'
  get 'workers/new'
  get 'home/index'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",registrations: "users/registrations"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions",registrations: "admins/registrations"}
  root to: 'home#index'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Safai", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? || admin_signed_in?%>
          <% if current_admin %>
          <li><%= link_to('Worker',workers_path)%></li>
          <li><%= link_to "New Worker", new_worker_path, class: "active" %></li>
          <li><%= link_to "Account", edit_admin_registration_path %></li>
          <li><%= link_to('Logout', destroy_admin_session_path, method: :delete) %></li>
          <% elsif current_user %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <% end %>
        <% else %>
        <li><%= link_to('Head Login', new_admin_session_path) %></li>
        <li><%= link_to('Worker Login', new_user_session_path)  %></li>
        <% end %>
      </ul>
      <!-- <form class= "navbar-form navbar-right", role: "search" >
         <p>
           <%= text_field_tag :search, params[:search], class: "form-control" %>
           <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
         </p>
       </form> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Safai</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>
</head>
<body>
    <%= render 'layouts/header' %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
  </div>


</body>
</html>